### ISSUE TITLE
Blue unreadable

### ISSUE THREAD

**Issue by PyGamer0** [McAuleyPenney/vim-dissonance#1]
Look at the foreground color of the tree. The blue is too dark.

![image](https://user-images.githubusercontent.com/64531844/113856169-82dc7b00-97be-11eb-97ee-6cc039a10329.png)

**Comment by McAuleyPenney** [comment]
I've been working on other projects and actually just now saw this. I'll address this right now!

**Comment by McAuleyPenney** [comment]
I believe that I modified the offending value, unless it's a highlight group that I don't have listed

**Comment by PyGamer0** [comment]
The tree I am using uses the `Directory` highlight group.

**Comment by McAuleyPenney** [comment]
Have you tried modifying the value yourself since you created the original issue posting?
